adulting/adulting/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("home/", include("home.urls")),
    path('budgets/', include('budgets.urls')),
    path('admin/', admin.site.urls),

]

adulting/budgets/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = "budgets"

urlpatterns = [
    path("<str:username>", views.index, name="index"),
    path("categories/<str:username>/<str:budget_name>/<int:budget_id>", views.categories, name="categories"),
    path("entries/<str:username>/<str:category_name>/<int:category_id>", views.entries, name="entries"),
]

adulting/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register_view, name="register"),
    path("account/newuser", views.newuser_view, name="newuser"),
    path("account/created", views.create_view, name="create"),
    path("account/changed", views.change_view, name="change"),
    path("account/<str:username>", views.account_view, name="account"),
]

adulting/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register_view, name="register"),
    path("account/newuser", views.newuser_view, name="newuser"),
    path("account/created", views.create_view, name="create"),
    path("account/changed", views.change_view, name="change"),
    path("account/<str:username>", views.account_view, name="account"),
]

adulting/budgets/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Budget(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    budget_text = models.CharField("Description", max_length=200)
    funds = models.IntegerField("Initial Funds")
    start_date = models.DateField("Start Date")
    end_date = models.DateField("End Date")

    def __str__(self):
        return self.budget_text

class Category(models.Model):
    budget = models.ForeignKey(Budget, on_delete=models.CASCADE)
    category_text = models.CharField("Description", max_length=200)

    def __str__(self):
        return self.category_text

class Entry(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    entry_text = models.CharField("Description", max_length=200)
    costs = models.IntegerField()

    def __str__(self):
        return self.entry_text

adulting/budgets/views.py
from django.shortcuts import render
#from django.urls import reverse
#from django.contrib.auth.models import User

from .models import Budget, Category, Entry

# Create your views here.

# View showing list of all budgets of the user
def index(request, username):
    if not request.user.is_authenticated:
        return render(request, "login/login.html", {
                "message": "Access denied. You need to log in first."
            })
    elif not username == request.user.username:
        return render(request, "budgets/index.html", {
            "message": "Access denied. These are not the budgets you're looking for."
        })
    else:
        budget_list = Budget.objects.filter(owner = request.user)
        context = {
            "budget_list": budget_list
        }
        return render(request, "budgets/index.html", context)

# View listing all the categories of a specific budget
def categories(request, username, budget_name, budget_id):
    if not request.user.is_authenticated:
        return render(request, "login/login.html", {
                "message": "Access denied. You need to log in first."
            })
    elif not username == request.user.username:
        return render(request, "budgets/index.html", {
            "message": "Access denied. These are not the budgets you're looking for."
        })
    else:
        category_list = Category.objects.filter(budget_id=budget_id)
        context = {
            "category_list": category_list,
            "budget_name": budget_name
        }
        return render(request, "budgets/categories.html", context)

# View showing all the entries of a category
def entries(request, username, category_name, category_id):
    if not request.user.is_authenticated:
        return render(request, "login/login.html", {
                "message": "Access denied. You need to log in first."
            })
    elif not username == request.user.username:
        return render(request, "budgets/index.html", {
            "message": "Access denied. These are not the budgets you're looking for."
        })
    else:
        entry_list = Entry.objects.filter(category_id=category_id)
        context = {
            "entry_list": entry_list,
            "category_name": category_name
        }
        return render(request, "budgets/entries.html", context)

adulting/budgets/templates/budgets/categories.html
{% extends 'budgets/layout.html' %}
{% load budgets_extras %}

{% block title %}{{budget_name}}{% endblock title %}

{% block content %}
{% include 'budgets/navigation.html' %}
<h1>{{budget_name}}</h1>
{% if message %}
    <div class="message">{{ message }}</div>
{% elif category_list %}
    <table>
        <tr>
            <th>Categories</th>
            <th colspan="2">Costs</th>
        </tr>
    {% for category in category_list  %}
        <tr>
            <td>
                <a href=" {% url 'budgets:entries' username=user.username category_name=category.category_text category_id=category.id %} ">{{ category.category_text}}</a>
            </td>
            <td>sFr. {% get_category_costs category %}.-</td>
            <td class="btn_anker"><a href="{% url 'home:index' %}" >Edit</a></td>
    {% endfor %}
    </table>
{% else %}
    <p>No categories available.</p>
{% endif %}
{% endblock content %}

adulting/budgets/templates/budgets/entries.html
{% extends 'budgets/layout.html' %}

{% block title %}{{category_name}}{% endblock title %}

{% block content %}
{% include 'budgets/navigation.html' %}
<h1>{{category_name}}</h1>
{% if message %}
    <div class="message">{{ message }}</div>
{% elif entry_list %}
    <table>
        <tr>
            <th>Entry</th>
            <th colspan="2">Costs</th>
        </tr>
    {% for entry in entry_list  %}
        <tr>
            <td>{{ entry.entry_text}}</td>
            <td>sFr. {{entry.costs}}.-</td>
            <td class="btn_anker"><a href="{% url 'home:index' %}" >Edit</a></td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No entries available.</p>
{% endif %}
{% endblock content %}

adulting/budgets/templates/budgets/index.html
{% extends 'budgets/layout.html' %}
{% load budgets_extras %}

{% block title %}Budgets{% endblock title %}

{% block content %}
{% include 'budgets/navigation.html' %}
<h1>Budgets</h1>
{% if message %}
<div class="message">{{ message }}</div>
{% elif budget_list %}
    <table>
        <tr>
            <th>Description</th>
            <th>Funds</th>
            <th>Costs</th>
            <th>Savings</th>
            <th colspan="2">Timeperiod</th>
        </tr>
    {% for budget in budget_list  %}
        <tr>
            <td><a href=" {% url 'budgets:categories' username=user.username budget_id=budget.id budget_name=budget.budget_text %} ">{{ budget.budget_text}}<a/></td>
            <td>sFr. {{budget.funds}}.-</td>
            <td>sFr. {% get_budget_costs budget %}.-</td>
            <td>sFr.{% get_savings budget %}</td>
            <td>{{budget.start_date}} - {{budget.end_date}}</td>
            <div class="btn_hover">
            <td class="btn_anker"><a href="{% url 'home:index' %}" >Edit</a></td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No budgets are available.</p>
{% endif %}

{% endblock content %}

adulting/budgets/templates/budgets/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href=" {% static 'budgets/budgets.css' %} "> 
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <section class="content">
    {% block content %}
    {% endblock %}
    </section>  
</body>
</html>

adulting/budgets/templates/budgets/navigation.html
<nav id="navbar" class="nav">
    <ul class="nav-list">
        <li><a href=" {% url 'users:index' %} ">Home</a></li>
        <li><a href=" {% url 'budgets:index' username=user.username%} ">Budgets</a></li>
        
    </ul>
    <ul class="modnav"> 
        <li><a href=" {% url 'users:account' username=user.username %}">Account</a></li>
        <li><a href=" {% url 'users:logout' %} ">Log Out</a></li> 
    </ul>
</nav>