adulting/adulting/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("home/", include("home.urls")),
    path('budgets/', include('budgets.urls')),
    path('admin/', admin.site.urls),

]

adulting/budgets/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = "budgets"

urlpatterns = [
    path("<str:username>", views.index, name="index"),
    path("categories/<str:username>/<str:budget_name>/<int:budget_id>", views.categories, name="categories"),
    path("entries/<str:username>/<str:category_name>/<int:category_id>", views.entries, name="entries"),
]

adulting/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register_view, name="register"),
    path("account/newuser", views.newuser_view, name="newuser"),
    path("account/created", views.create_view, name="create"),
    path("account/changed", views.change_view, name="change"),
    path("account/<str:username>", views.account_view, name="account"),
]

adulting/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register_view, name="register"),
    path("account/newuser", views.newuser_view, name="newuser"),
    path("account/created", views.create_view, name="create"),
    path("account/changed", views.change_view, name="change"),
    path("account/<str:username>", views.account_view, name="account"),
]

adulting/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import  HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from django.contrib.auth.models import User

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return render(request, "users/user.html")

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("users:index"))
        else:
            return render(request, "users/login.html", {
                "message": "Invalid credentials."
            })
    else:
        return render(request, "users/login.html")
    
def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {
        "message": "Logged out."
    })

def register_view(request):
    if not request.user.is_authenticated:
        return render(request, "users/new_user.html")
    else:
        return render(request, "users/user.html")

def account_view(request, username):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {
                "message": "Access denied. You need to log in first."
            })
    elif not username == request.user.username and not request.user.is_superuser:
        return render(request, "users/user.html", {
            "message": "Access denied. That's not your account."
        })
    else:
        account = User.objects.filter(username=username)[0] 
        accounts = User.objects.all()
        context ={
            "account": account,
            "accounts": accounts,
            "username": username
        }
        return render(request, "users/account.html", context)

def change_view(request):
    if request.method == "POST":
        user_id = request.user.id
        new = None
        new = User.objects.filter(id=user_id).get()
        username = request.POST["username"] 
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]  
        new.username = username
        new.first_name = request.POST["first_name"]
        new.last_name = request.POST["last_name"]
        new.email = request.POST["email"] 
        if password != confirmation:
            return render(request, "users/user.html", { "message": "Passwords do not match."} )
        elif len(password) > 0 :
            new.set_password(password)
            new.save()
            return HttpResponseRedirect(reverse("users:login"))
        else:
            new.save()
            return HttpResponseRedirect(reverse("users:index"))
    else:
        return render(request, "users/user.html")

def newuser_view(request):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {
                "message": "Access denied. You need to log in first."
            })
    elif request.user.is_superuser:
        return render(request, "users/new_user.html")
    else:
        return render(request, "users/user.html", {
            "message": "You shall not pass."
        })
    
def create_view(request):
    if request.method == "POST":
        superuser = request.POST["superuser"] 
        username = request.POST["username"]
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]   
        if password == confirmation:
            if superuser == "YES":
                new_usr = User.objects.create_superuser(username, password=password)
                new_usr.first_name = request.POST["first_name"]
                new_usr.last_name = request.POST["last_name"]
                new_usr.email = request.POST["email"]
                new_usr.save()
                return HttpResponseRedirect(reverse("users:newuser"))
            else:
                new_usr = User.objects.create_user(username, password=password)
                new_usr.first_name = request.POST["first_name"]
                new_usr.last_name = request.POST["last_name"]
                new_usr.email = request.POST["email"]
                new_usr.save()
                return HttpResponseRedirect(reverse("users:newuser"))
    else:
        return render(request, "users/new_user.html")

adulting/users/templates/users/account.html
{% extends 'users/layout.html' %}

{% block title %}Account | {{username}}{% endblock title %}

{% block content %}
    {% if request.user.is_superuser %}
        {% include "users/nav_adm.html" %}
    {% else %}
        {% include "users/navigation.html" %}
    {% endif %}
    <div class="content" id="account">
        <h1>{{username}}</h1>

        {% if message %}
            <div class="message"><strong>{{message}}</strong></div>
        {% endif %}

        <form action=" {% url 'users:change' %} " method="post">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" id="username" value="{{username}}" required>
            <label for="first_name">First Name</label>
            <input type="text" name="first_name" id="first_name" value="{{account.first_name}}">
            <label for="last_name">Last Name</label>
            <input type="text" name="last_name" id="last_name" value="{{account.last_name}}">
            <label for="email">Email</label>
            <input type="email" name="email" id="email" value="{{account.email}}">
            <label for="password">Password</label>
            <input type="password" name="password" id="password">
            <label for="confirmation">Confirm Password</label>
            <input type="password" name="confirmation" id="confirmation">
            <fieldset>
                <input type="submit" value="Save"> 
                <input type="reset" value="Cancel">
            </fieldset>
        </form>
    </div>
{% endblock content %}


{% block addons %}
    {% if request.user.is_superuser %}
    <section class="content" id="accounts"> 
        <h2>Accounts</h2>

        <table>
            <tr>
                <td>Username</td>
                <td colspan="2">Email</td>
            </tr>
            {% for account in accounts  %}
            <tr>
                <td>{{account.username}}</td>
                <td>{{account.email}}</td>
                <td class="tanker"><a href="{% url 'users:account' username=account.username %}">Edit</a></td>
            </tr>
            {% endfor %}
        </table>

    </section>
    {% endif %}
{% endblock addons %}

adulting/users/templates/users/login.html
{% extends "users/layout.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
{% include "users/login_banner.html" %}

    <h1>Log In</h1>

    {% if message %}
        <div class="message">{{ message }}</div>
    {% endif %}

    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username">
        <label for="password">Password</label>
        <input type="password" name="password">
        <fieldset>
            <input type="submit" value="Login">
            <button type="button"> <a href="{% url 'users:register' %}" class="button">Register New Account</a></button>
        </fieldset>
    </form>

{% endblock %}

adulting/users/templates/users/nav_adm.html
<nav id="navbar" class="nav">
    <ul class="nav-list">
        <li><a href=" {% url 'users:index' %} ">Home</a></li>
        <li><a href=" {% url 'budgets:index' username=user.username %} ">Budgets</a></li>
        
    </ul>
    <ul class="modnav"> 
        <li><a href="#account">Account</a></li>
        <li><a href="#accounts">Accounts</a></li>
        <li><a href="{% url 'users:newuser' %}">Create New User</a></li>
        <li><a href=" {% url 'users:logout' %} ">Log Out</a></li> 
    </ul>
</nav>

adulting/users/templates/users/new_user.html
{% extends 'users/layout.html' %}

{% block title %}Register{% endblock title %}

{% block content %}
{% if request.user.is_authenticated %}
{% include "users/navigation.html" %}
{% else %}
{% include "users/login_banner.html" %}
{% endif %}


<h1>Register</h1>

{% if message %}
    <div class="message"><strong>{{message}}</strong></div>
{% endif %}

<form action=" {% url 'users:create' %} " method="post">
    {% csrf_token %}
    <fieldset class="field-col">
        <legend>Required</legend>
        <label for="username">Username</label>
        <input type="text" name="username" id="username" required>
        <label for="password">Password</label>
        <input type="password" name="password" id="password" required>
        <label for="confirmation">Confirm Password</label>
        <input type="password" name="confirmation" id="confirmation" required>
        {% if request.user.is_superuser %}
        <fieldset>
            <legend>Superuser</legend>
            <input type="radio" name="superuser" id="yes" value="YES" required>
            <label for="yes">Yes</label>
            <input type="radio" name="superuser" id="no" value="NO" required>
            <label for="no">No</label>            
        </fieldset>
        {% else %}
        <input type="hidden" name="superuser" id="no" value="NO">       
        {% endif %}
    
    </fieldset>
    <fieldset class="field-col">
        <legend>Optional</legend>
        <label for="first_name">First Name</label>
        <input type="text" name="first_name" id="first_name">
        <label for="last_name">Last Name</label>
        <input type="text" name="last_name" id="last_name">
        <label for="email">Email</label>
        <input type="email" name="email" id="email">
    </fieldset>
    <fieldset>
        <input type="submit" value="Submit"> 
        <input type="reset" value="Cancel">
    </fieldset>
</form>


{% endblock content %}

adulting/users/templates/users/user.html
{% extends "users/layout.html" %}

{% block title %}Home{% endblock title %}

{% block content %}
{% include "users/navigation.html" %}

<h1>Welcome, {{ request.user.first_name }}</h1>

{% if message %}
    <div class="message"><strong>{{message}}</strong></div>
{% endif %}

<table>
    <tr>
        <td>
            <p>
                The intent of this project is to offer applications that help you with all the boring, tedious stuff that comes with adulthood. You know...responsibilities.
            </p>
        </td>
    </tr>
    <tr>
        <td>
            <p>At the moment, the only app available is the budget app. <br> Home will bring you back to this page. <br> Account gives you an overview of your account and also allows you to edit your information.</p>
        </td>
    </tr>
</table>


{% endblock %}